### PR TITLE
plz update readme

### PR DESCRIPTION
**Pull request by pandablue0809**
git clone git@github.com:MIMBCD-UI/dicom-server.git
this is 404
thank you

### CODE REVIEW

**Comment by FMCalisto** [comment]
Thank you, @pandablue0809, for your contribution in fixing the README! Your attention to detail helps improve the usability of the repository. I appreciate your effort in making this project better for everyone!

**Comment by pandablue0809** [comment]
thank you
could you invite me in your organization

**Comment by FMCalisto** [comment]
We have added you. Welcome and congratulations!

**Comment by pandablue0809** [comment]
thx

**Pull request merged**
